using Microsoft.Extensions.Localization;
using System.Collections.Concurrent;
using System.Globalization;

namespace TeknoSOS.WebApp.Services
{
    /// <summary>
    /// Simple JSON-like localization service for TeknoSOS.
    /// Supports: sq (Albanian), en (English), it (Italian), de (German), fr (French)
    /// </summary>
    public interface ILocalizationService
    {
        string T(string key);
        string T(string key, params object[] args);
        string CurrentLanguage { get; }
        IReadOnlyList<LanguageOption> AvailableLanguages { get; }
    }

    public class LanguageOption
    {
        public string Code { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string NativeName { get; set; } = string.Empty;
        public string Flag { get; set; } = string.Empty;
    }

    public class LocalizationService : ILocalizationService
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private static readonly ConcurrentDictionary<string, Dictionary<string, string>> _translations = new();

        public static readonly List<LanguageOption> Languages = new()
        {
            new() { Code = "sq", Name = "Albanian", NativeName = "Shqip", Flag = "🇦🇱" },
            new() { Code = "en", Name = "English", NativeName = "English", Flag = "🇬🇧" },
            new() { Code = "it", Name = "Italian", NativeName = "Italiano", Flag = "🇮🇹" },
            new() { Code = "de", Name = "German", NativeName = "Deutsch", Flag = "🇩🇪" },
            new() { Code = "fr", Name = "French", NativeName = "Français", Flag = "🇫🇷" }
        };

        public LocalizationService(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            InitializeTranslations();
        }

        public string CurrentLanguage
        {
            get
            {
                var lang = _httpContextAccessor.HttpContext?.Request.Cookies["teknosos_lang"];
                if (string.IsNullOrEmpty(lang) || !_translations.ContainsKey(lang))
                    return "sq"; // Default to Albanian
                return lang;
            }
        }

        public IReadOnlyList<LanguageOption> AvailableLanguages => Languages;

        public string T(string key)
        {
            var lang = CurrentLanguage;
            if (_translations.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var value))
                return value;
            // Fallback to Albanian, then English, then key itself
            if (_translations.TryGetValue("sq", out var sqDict) && sqDict.TryGetValue(key, out var sqValue))
                return sqValue;
            if (_translations.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enValue))
                return enValue;
            return key;
        }

        public string T(string key, params object[] args)
        {
            var template = T(key);
            try { return string.Format(template, args); }
            catch { return template; }
        }

        private static void InitializeTranslations()
        {
            if (_translations.Count > 0) return;

            // ======== ALBANIAN (sq) - Primary Language ========
            _translations["sq"] = new Dictionary<string, string>
            {
                // Navigation
                ["nav.home"] = "Kryefaqja",
                ["nav.dashboard"] = "Paneli",
                ["nav.about"] = "Rreth Nesh",
                ["nav.how_it_works"] = "Si Funksionon",
                ["nav.contact"] = "Kontakt",
                ["nav.faq"] = "Pyetje të Shpeshta",
                ["nav.login"] = "Hyr",
                ["nav.register"] = "Regjistrohu",
                ["nav.logout"] = "Dil",
                ["nav.profile"] = "Profili",
                ["nav.messages"] = "Mesazhet",
                ["nav.report_defect"] = "Raporto Defekt",
                ["nav.my_reports"] = "Raportet e Mia",
                ["nav.admin"] = "Admin Panel",
                ["nav.language"] = "Gjuha",

                // Footer
                ["footer.quick_links"] = "Lidhje të Shpejta",
                ["footer.legal"] = "Ligjore",
                ["footer.about_us"] = "Rreth Nesh",
                ["footer.contact"] = "Kontakt",
                ["footer.privacy"] = "Politika e Privatësisë",
                ["footer.terms"] = "Kushtet e Përdorimit",
                ["footer.cookies"] = "Politika e Cookies",
                ["footer.disclaimer"] = "Kufizim Përgjegjësie",
                ["footer.rights"] = "Të gjitha të drejtat e rezervuara.",
                ["footer.made_in"] = "Ndërtuar me dashamirësi në Shqipëri",

                // Home Page
                ["home.title"] = "Kryefaqja",
                ["home.hero_title"] = "TeknoSOS",
                ["home.hero_subtitle"] = "Lidhuni me profesionistë të certifikuar për të gjitha nevojat tuaja teknike. Shpejt, me besim dhe të verifikuar.",
                ["home.get_started"] = "Fillo Tani",
                ["home.sign_in"] = "Identifikohu",
                ["home.go_dashboard"] = "Shko në Panel",
                ["home.for_clients"] = "Për Klientët",
                ["home.for_clients_desc"] = "Postoni nevojat tuaja për shërbim dhe lidhuni me profesionistë të verifikuar menjëherë.",
                ["home.for_professionals"] = "Për Profesionistët",
                ["home.for_professionals_desc"] = "Rritni biznesin tuaj duke ofruar shërbime për mijëra klientë pranë jush.",
                ["home.verified"] = "I Verifikuar & i Sigurt",
                ["home.verified_desc"] = "Të gjitha transaksionet janë të siguruara me platformën tonë të besueshme.",
                ["home.how_it_works"] = "Si Funksionon",
                ["home.step1_title"] = "Posto Kërkesën",
                ["home.step1_desc"] = "Përshkruaj problemin me foto dhe vendndodhje",
                ["home.step2_title"] = "Merr Oferta",
                ["home.step2_desc"] = "Merr oferta nga profesionistë të certifikuar pranë teje",
                ["home.step3_title"] = "Zgjidh & Puno",
                ["home.step3_desc"] = "Zgjidh bazuar në vlerësime dhe komente",
                ["home.step4_title"] = "Lër Vlerësim",
                ["home.step4_desc"] = "Vlerëso dhe komento profesionistin",
                ["home.cta_title"] = "Gati për të filluar?",
                ["home.cta_subtitle"] = "Bashkohu me mijëra klientë dhe profesionistë të kënaqur",
                ["home.create_account"] = "Krijo Llogari",
                ["home.already_account"] = "Ke llogari? Identifikohu",

                // Home - new keys
                ["home.subtitle"] = "Platforma Dixhitale e Shërbimeve Teknike",
                ["home.description"] = "Lidhuni me profesionistë të certifikuar për të gjitha nevojat tuaja teknike. Shpejt, me besim dhe të verifikuar.",
                ["home.services_title"] = "Shërbimet Tona",
                ["home.services_subtitle"] = "Zgjidhni kategorinë e shërbimit që ju nevojitet",
                ["home.cat_plumbing"] = "Hidraulikë",
                ["home.cat_electrical"] = "Elektrike",
                ["home.cat_hvac"] = "Ngrohje/Ftohje",
                ["home.cat_carpentry"] = "Zdrukthtari",
                ["home.cat_appliance"] = "Pajisje",
                ["home.cat_general"] = "Përgjithshme",
                ["home.client_step1"] = "Përshkruaj problemin tuaj",
                ["home.client_step2"] = "Merr oferta profesionale",
                ["home.client_step3"] = "Lër vlerësime të verifikuara",
                ["home.pro_step1"] = "Merr oferta pune",
                ["home.pro_step2"] = "Ndërto reputacionin tuaj",
                ["home.pro_step3"] = "Fito me besueshmëri",
                ["home.verified_secure"] = "I Verifikuar & i Sigurt",
                ["home.secure_step1"] = "Profesionistë të verifikuar",
                ["home.secure_step2"] = "Transaksione të siguruara",
                ["home.secure_step3"] = "Vlerësime nga komuniteti",
                ["home.step1"] = "Posto Kërkesën",
                ["home.step1_desc"] = "Përshkruaj problemin me foto dhe vendndodhje",
                ["home.step2"] = "Merr Oferta",
                ["home.step2_desc"] = "Merr oferta nga profesionistë të certifikuar pranë teje",
                ["home.step3"] = "Zgjidh & Puno",
                ["home.step3_desc"] = "Zgjidh bazuar në vlerësime dhe komente",
                ["home.step4"] = "Lër Vlerësim",
                ["home.step4_desc"] = "Vlerëso dhe komento profesionistin",
                ["home.stat_professionals"] = "Profesionistë",
                ["home.stat_completed"] = "Punë të Kryera",
                ["home.stat_rating"] = "Vlerësimi Mesatar",
                ["home.stat_response"] = "Koha e Përgjigjes",

                // Nav extras
                ["nav.terms"] = "Kushtet",
                ["nav.privacy"] = "Privatësia",
                ["nav.cookies"] = "Cookies",
                ["nav.disclaimer"] = "Kufizim",
                ["nav.notifications"] = "Njoftimet",
                ["nav.technicians"] = "Tekniket",
                ["technicians_title"] = "Tekniket Tane",

                // Footer extras
                ["footer.description"] = "Platforma lider dixhitale për lidhjen e qytetarëve me profesionistë teknikë në Shqipëri.",
                ["footer.navigation"] = "Navigimi",

                // Defects extras
                ["defects.timeline"] = "Historiku i Statusit",
                ["defects.messages"] = "Mesazhet",
                ["defects.client"] = "Klienti",
                ["defects.professional"] = "Profesionisti",
                ["defects.created_date"] = "Data e Krijimit",
                ["defects.scheduled_date"] = "Data e Planifikuar",
                ["defects.completed_date"] = "Data e Përfundimit",
                ["defects.estimated_cost"] = "Kostoja e Vlerësuar",
                ["defects.final_cost"] = "Kostoja Finale",
                ["defects.not_found"] = "Defekti nuk u gjet.",
                ["defects.confirm_cancel"] = "Jeni të sigurt që doni të anuloni?",
                ["defects.cancel_request"] = "Anulo Kërkesën",
                ["defects.mark_complete"] = "Shëno si të Përfunduar",

                // About Page
                ["about.title"] = "Rreth Nesh",
                ["about.hero_title"] = "Rreth TeknoSOS",
                ["about.hero_subtitle"] = "Platforma lider në Shqipëri për lidhjen e qytetarëve me profesionistë teknikë të certifikuar.",
                ["about.mission_title"] = "Misioni Ynë",
                ["about.mission_text"] = "TeknoSOS u krijua me vizionin për të transformuar mënyrën se si qytetarët në Shqipëri gjejnë dhe punësojnë profesionistë teknikë. Ne besojmë se çdo person meriton qasje të shpejtë, transparente dhe të sigurt në shërbime cilësore teknike.",
                ["about.what_we_do_title"] = "Çfarë Bëjmë",
                ["about.what_we_do_text"] = "Ne lidhim qytetarët me profesionistë të verifikuar për shërbime hidraulike, elektrike, HVAC, zdrukthtarie dhe riparime të përgjithshme. Platforma jonë siguron transparencë të plotë, vlerësime reale dhe mbrojtje për të dy palët.",
                ["about.values_title"] = "Vlerat Tona",
                ["about.value_trust"] = "Besim",
                ["about.value_trust_desc"] = "Çdo profesionist kontrollohet dhe verifikohet para se të hyjë në platformë.",
                ["about.value_quality"] = "Cilësi",
                ["about.value_quality_desc"] = "Vetëm profesionistë me përvojë dhe aftësi të dëshmuara pranohen.",
                ["about.value_transparency"] = "Transparencë",
                ["about.value_transparency_desc"] = "Çmimet, vlerësimet dhe komentet janë gjithmonë të dukshme.",
                ["about.value_speed"] = "Shpejtësi",
                ["about.value_speed_desc"] = "Lidhje e menjëhershme me profesionistë në zonën tuaj.",
                ["about.team_title"] = "Ekipi Ynë",
                ["about.team_text"] = "Ekipi i TeknoSOS përbëhet nga profesionistë me përvojë në teknologji, zhvillim biznesi dhe shërbime ndaj klientit. Jemi të përkushtuar për të ofruar përvojën më të mirë si për klientët ashtu edhe për profesionistët.",

                // How It Works Page
                ["how.title"] = "Si Funksionon",
                ["how.hero_title"] = "Si Funksionon TeknoSOS",
                ["how.hero_subtitle"] = "Procesi ynë i thjeshtë dhe efektiv për të lidhur klientët me profesionistë.",
                ["how.for_clients_title"] = "Për Klientët",
                ["how.client_step1"] = "Krijo një kërkesë për shërbim duke përshkruar problemin",
                ["how.client_step2"] = "Ngarko foto, specifiko vendndodhjen dhe urgjencën",
                ["how.client_step3"] = "Merr oferta nga profesionistë të verifikuar",
                ["how.client_step4"] = "Zgjidh profesionistin bazuar në vlerësime dhe çmime",
                ["how.client_step5"] = "Pas përfundimit, lër një vlerësim",
                ["how.for_pros_title"] = "Për Profesionistët",
                ["how.pro_step1"] = "Krijoni profilin tuaj profesional me specialitetet",
                ["how.pro_step2"] = "Shikoni kërkesat për shërbim në zonën tuaj",
                ["how.pro_step3"] = "Dërgoni oferta me çmim dhe kohë të vlerësuar",
                ["how.pro_step4"] = "Pranoni punën kur klienti ju zgjedh",
                ["how.pro_step5"] = "Përfundoni punën dhe merrni vlerësime pozitive",

                // Contact Page
                ["contact.title"] = "Kontakt",
                ["contact.hero_title"] = "Na Kontaktoni",
                ["contact.hero_subtitle"] = "Keni pyetje? Na shkruani dhe do t'ju përgjigjem brenda 24 orëve.",
                ["contact.name"] = "Emri i Plotë",
                ["contact.email"] = "Email",
                ["contact.subject"] = "Subjekti",
                ["contact.message"] = "Mesazhi",
                ["contact.send"] = "Dërgo Mesazhin",
                ["contact.address_title"] = "Adresa",
                ["contact.address"] = "Tiranë, Shqipëri",
                ["contact.phone"] = "+355 69 XXX XXXX",
                ["contact.email_address"] = "info@teknosos.al",
                ["contact.hours_title"] = "Orari",
                ["contact.hours"] = "E Hënë - E Premte: 08:00 - 17:00",
                ["contact.success"] = "Mesazhi u dërgua me sukses! Do t'ju kontaktojmë së shpejti.",

                // FAQ Page
                ["faq.title"] = "Pyetje të Shpeshta",
                ["faq.hero_title"] = "Pyetje të Shpeshta (FAQ)",
                ["faq.hero_subtitle"] = "Gjeni përgjigjet e pyetjeve më të zakonshme rreth TeknoSOS.",
                ["faq.q1"] = "Çfarë është TeknoSOS?",
                ["faq.a1"] = "TeknoSOS është platformë online që lidh qytetarët me profesionistë teknikë të verifikuar në Shqipëri. Ju mundëson të raportoni defekte, të gjeni profesionistë dhe të menaxhoni kërkesat e shërbimit.",
                ["faq.q2"] = "A është falas përdorimi i platformës?",
                ["faq.a2"] = "Po, regjistrimi dhe postimi i kërkesave është falas për qytetarët. Profesionistët mund të kenë plane me pagesë për mundësi shtesë.",
                ["faq.q3"] = "Si verifikohen profesionistët?",
                ["faq.a3"] = "Çdo profesionist kalon një proces verifikimi që përfshin kontrollin e identitetit, kualifikimeve dhe përvojës së punës. Vetëm ata që plotësojnë standardet tona pranohen.",
                ["faq.q4"] = "Si funksionon procesi i raportimit të defekteve?",
                ["faq.a4"] = "Hyni në llogarinë tuaj, shkoni tek 'Raporto Defekt', plotësoni formularin me detaje, foto dhe vendndodhje. Kërkesa juaj do të jetë e dukshme për profesionistët e zonës.",
                ["faq.q5"] = "Cilat zona mbulohen?",
                ["faq.a5"] = "Aktualisht mbulojmë të gjithë Shqipërinë, me fokus të veçantë në Tiranë, Durrës, Vlorë, Shkodër dhe Elbasan.",
                ["faq.q6"] = "Si mund të bëhem profesionist në platformë?",
                ["faq.a6"] = "Regjistrohuni si profesionist, plotësoni profilin tuaj me specialitete dhe dokumente, dhe prisni miratimin nga ekipi ynë.",
                ["faq.q7"] = "A janë të sigurta pagesat?",
                ["faq.a7"] = "Po, të gjitha transaksionet processohen nëpërmjet sistemeve të siguruara. Ne nuk ruajmë të dhënat e kartave tuaja.",
                ["faq.q8"] = "Si mund të kontaktoj mbështetjen?",
                ["faq.a8"] = "Mund të na kontaktoni nëpërmjet faqes së kontaktit, emailit info@teknosos.al ose telefonit gjatë orarit të punës.",

                // Terms & Conditions
                ["terms.title"] = "Kushtet e Përdorimit",

                // Privacy Policy
                ["privacy.title"] = "Politika e Privatësisë",

                // Cookie Policy
                ["cookies.title"] = "Politika e Cookies",

                // Disclaimer
                ["disclaimer.title"] = "Kufizim Përgjegjësie",

                // Defect Pages
                ["defects.title"] = "Defektet",
                ["defects.list_title"] = "Lista e Defekteve",
                ["defects.my_reports"] = "Raportet e Mia",
                ["defects.report_new"] = "Raporto Defekt të Ri",
                ["defects.status"] = "Statusi",
                ["defects.category"] = "Kategoria",
                ["defects.priority"] = "Prioriteti",
                ["defects.date"] = "Data",
                ["defects.location"] = "Vendndodhja",
                ["defects.description"] = "Përshkrimi",
                ["defects.no_reports"] = "Nuk keni asnjë raport ende.",
                ["defects.details_title"] = "Detajet e Defektit",
                ["defects.status_created"] = "Krijuar",
                ["defects.status_matched"] = "Përputhur",
                ["defects.status_in_progress"] = "Në Proces",
                ["defects.status_completed"] = "Përfunduar",
                ["defects.status_cancelled"] = "Anuluar",
                ["defects.status_rejected"] = "Refuzuar",
                ["defects.interests"] = "Interesat e Teknikëve",
                ["defects.no_interests"] = "Ende nuk ka interes nga teknikët.",

                // Admin Panel
                ["admin.title"] = "Paneli i Administrimit",
                ["admin.dashboard"] = "Paneli Kryesor",
                ["admin.users"] = "Përdoruesit",
                ["admin.defects"] = "Defektet",
                ["admin.settings"] = "Cilësimet",
                ["admin.site_settings"] = "Cilësimet e Faqes",
                ["admin.logo"] = "Logo",
                ["admin.colors"] = "Ngjyrat",
                ["admin.content"] = "Përmbajtja",
                ["admin.languages"] = "Gjuhët",
                ["admin.navigation"] = "Navigimi",
                ["admin.total_users"] = "Përdorues Gjithsej",
                ["admin.total_defects"] = "Defekte Gjithsej",
                ["admin.pending"] = "Në Pritje",
                ["admin.active_pros"] = "Profesionistë Aktivë",

                // Common
                ["common.save"] = "Ruaj",
                ["common.cancel"] = "Anulo",
                ["common.delete"] = "Fshi",
                ["common.edit"] = "Ndrysho",
                ["common.view"] = "Shiko",
                ["common.search"] = "Kërko",
                ["common.filter"] = "Filtro",
                ["common.loading"] = "Duke ngarkuar...",
                ["common.no_results"] = "Nuk u gjetën rezultate.",
                ["common.confirm"] = "Konfirmo",
                ["common.back"] = "Kthehu",
                ["common.next"] = "Vazhdo",
                ["common.submit"] = "Dërgo",
                ["common.actions"] = "Veprimet",
                ["common.status"] = "Statusi",
                ["common.active"] = "Aktiv",
                ["common.inactive"] = "Joaktiv",
                ["common.role"] = "Roli",
                ["common.date"] = "Data",
                ["common.all"] = "Të gjitha",
            };

            // ======== ENGLISH (en) ========
            _translations["en"] = new Dictionary<string, string>
            {
                ["nav.home"] = "Home",
                ["nav.dashboard"] = "Dashboard",
                ["nav.about"] = "About Us",
                ["nav.how_it_works"] = "How It Works",
                ["nav.contact"] = "Contact",
                ["nav.faq"] = "FAQ",
                ["nav.login"] = "Login",
                ["nav.register"] = "Register",
                ["nav.logout"] = "Logout",
                ["nav.profile"] = "Profile",
                ["nav.messages"] = "Messages",
                ["nav.report_defect"] = "Report Defect",
                ["nav.my_reports"] = "My Reports",
                ["nav.admin"] = "Admin Panel",
                ["nav.language"] = "Language",

                ["footer.quick_links"] = "Quick Links",
                ["footer.legal"] = "Legal",
                ["footer.about_us"] = "About Us",
                ["footer.contact"] = "Contact",
                ["footer.privacy"] = "Privacy Policy",
                ["footer.terms"] = "Terms of Service",
                ["footer.cookies"] = "Cookie Policy",
                ["footer.disclaimer"] = "Disclaimer",
                ["footer.rights"] = "All rights reserved.",
                ["footer.made_in"] = "Made with love in Albania",

                ["home.title"] = "Home",
                ["home.hero_title"] = "TeknoSOS",
                ["home.hero_subtitle"] = "Connect with certified professionals for all your technical needs. Fast, reliable, and verified.",
                ["home.get_started"] = "Get Started",
                ["home.sign_in"] = "Sign In",
                ["home.go_dashboard"] = "Go to Dashboard",
                ["home.for_clients"] = "For Clients",
                ["home.for_clients_desc"] = "Post your service needs and get matched with verified professionals instantly.",
                ["home.for_professionals"] = "For Professionals",
                ["home.for_professionals_desc"] = "Grow your business by offering your services to thousands of clients nearby.",
                ["home.verified"] = "Verified & Secure",
                ["home.verified_desc"] = "All transactions secured with our trusted platform and community reviews.",
                ["home.how_it_works"] = "How It Works",
                ["home.step1_title"] = "Post a Request",
                ["home.step1_desc"] = "Describe your problem with photos and location",
                ["home.step2_title"] = "Receive Offers",
                ["home.step2_desc"] = "Get offers from certified professionals nearby",
                ["home.step3_title"] = "Select & Hire",
                ["home.step3_desc"] = "Choose based on ratings and reviews",
                ["home.step4_title"] = "Leave Review",
                ["home.step4_desc"] = "Rate and review the professional",
                ["home.cta_title"] = "Ready to get started?",
                ["home.cta_subtitle"] = "Join thousands of satisfied clients and professionals",
                ["home.create_account"] = "Create Account",
                ["home.already_account"] = "Already have an account? Sign In",

                // Home - new keys
                ["home.subtitle"] = "Digital Technical Services Platform",
                ["home.description"] = "Connect with certified professionals for all your technical needs. Fast, reliable, and verified.",
                ["home.services_title"] = "Our Services",
                ["home.services_subtitle"] = "Choose the service category you need",
                ["home.cat_plumbing"] = "Plumbing",
                ["home.cat_electrical"] = "Electrical",
                ["home.cat_hvac"] = "HVAC",
                ["home.cat_carpentry"] = "Carpentry",
                ["home.cat_appliance"] = "Appliance",
                ["home.cat_general"] = "General",
                ["home.client_step1"] = "Describe your problem",
                ["home.client_step2"] = "Get professional offers",
                ["home.client_step3"] = "Leave verified reviews",
                ["home.pro_step1"] = "Receive job offers",
                ["home.pro_step2"] = "Build your reputation",
                ["home.pro_step3"] = "Earn reliably",
                ["home.verified_secure"] = "Verified & Secure",
                ["home.secure_step1"] = "Verified professionals",
                ["home.secure_step2"] = "Secure transactions",
                ["home.secure_step3"] = "Community ratings",
                ["home.step1"] = "Post a Request",
                ["home.step1_desc"] = "Describe your problem with photos and location",
                ["home.step2"] = "Receive Offers",
                ["home.step2_desc"] = "Get offers from certified professionals nearby",
                ["home.step3"] = "Select & Hire",
                ["home.step3_desc"] = "Choose based on ratings and reviews",
                ["home.step4"] = "Leave Review",
                ["home.step4_desc"] = "Rate and review the professional",
                ["home.stat_professionals"] = "Professionals",
                ["home.stat_completed"] = "Jobs Completed",
                ["home.stat_rating"] = "Average Rating",
                ["home.stat_response"] = "Response Time",

                // Nav extras
                ["nav.terms"] = "Terms",
                ["nav.privacy"] = "Privacy",
                ["nav.cookies"] = "Cookies",
                ["nav.disclaimer"] = "Disclaimer",
                ["nav.notifications"] = "Notifications",
                ["nav.technicians"] = "Technicians",
                ["technicians_title"] = "Our Technicians",

                // Footer extras
                ["footer.description"] = "Albania's leading digital platform connecting citizens with technical professionals.",
                ["footer.navigation"] = "Navigation",

                // Defects extras
                ["defects.timeline"] = "Status Timeline",
                ["defects.messages"] = "Messages",
                ["defects.client"] = "Client",
                ["defects.professional"] = "Professional",
                ["defects.created_date"] = "Created Date",
                ["defects.scheduled_date"] = "Scheduled Date",
                ["defects.completed_date"] = "Completed Date",
                ["defects.estimated_cost"] = "Estimated Cost",
                ["defects.final_cost"] = "Final Cost",
                ["defects.not_found"] = "Defect not found.",
                ["defects.confirm_cancel"] = "Are you sure you want to cancel?",
                ["defects.cancel_request"] = "Cancel Request",
                ["defects.mark_complete"] = "Mark as Complete",

                ["about.title"] = "About Us",
                ["about.hero_title"] = "About TeknoSOS",
                ["about.hero_subtitle"] = "Albania's leading platform connecting citizens with certified technical professionals.",
                ["about.mission_title"] = "Our Mission",
                ["about.mission_text"] = "TeknoSOS was created with the vision to transform how citizens in Albania find and hire technical professionals. We believe everyone deserves fast, transparent, and secure access to quality technical services.",
                ["about.what_we_do_title"] = "What We Do",
                ["about.what_we_do_text"] = "We connect citizens with verified professionals for plumbing, electrical, HVAC, carpentry, and general repair services. Our platform ensures full transparency, real reviews, and protection for both parties.",
                ["about.values_title"] = "Our Values",
                ["about.value_trust"] = "Trust",
                ["about.value_trust_desc"] = "Every professional is screened and verified before joining our platform.",
                ["about.value_quality"] = "Quality",
                ["about.value_quality_desc"] = "Only professionals with proven experience and skills are accepted.",
                ["about.value_transparency"] = "Transparency",
                ["about.value_transparency_desc"] = "Prices, ratings, and reviews are always visible.",
                ["about.value_speed"] = "Speed",
                ["about.value_speed_desc"] = "Instant connection with professionals in your area.",
                ["about.team_title"] = "Our Team",
                ["about.team_text"] = "The TeknoSOS team consists of experienced professionals in technology, business development, and customer service. We are committed to delivering the best experience for both clients and professionals.",

                ["how.title"] = "How It Works",
                ["how.hero_title"] = "How TeknoSOS Works",
                ["how.hero_subtitle"] = "Our simple and effective process for connecting clients with professionals.",
                ["how.for_clients_title"] = "For Clients",
                ["how.client_step1"] = "Create a service request describing your problem",
                ["how.client_step2"] = "Upload photos, specify location and urgency",
                ["how.client_step3"] = "Receive offers from verified professionals",
                ["how.client_step4"] = "Choose a professional based on ratings and prices",
                ["how.client_step5"] = "After completion, leave a review",
                ["how.for_pros_title"] = "For Professionals",
                ["how.pro_step1"] = "Create your professional profile with specialties",
                ["how.pro_step2"] = "Browse service requests in your area",
                ["how.pro_step3"] = "Send offers with estimated price and time",
                ["how.pro_step4"] = "Accept the job when the client selects you",
                ["how.pro_step5"] = "Complete the job and earn positive reviews",

                ["contact.title"] = "Contact",
                ["contact.hero_title"] = "Contact Us",
                ["contact.hero_subtitle"] = "Have questions? Write to us and we'll respond within 24 hours.",
                ["contact.name"] = "Full Name",
                ["contact.email"] = "Email",
                ["contact.subject"] = "Subject",
                ["contact.message"] = "Message",
                ["contact.send"] = "Send Message",
                ["contact.address_title"] = "Address",
                ["contact.address"] = "Tirana, Albania",
                ["contact.phone"] = "+355 69 XXX XXXX",
                ["contact.email_address"] = "info@teknosos.al",
                ["contact.hours_title"] = "Hours",
                ["contact.hours"] = "Monday - Friday: 08:00 - 17:00",
                ["contact.success"] = "Message sent successfully! We'll contact you soon.",

                ["faq.title"] = "FAQ",
                ["faq.hero_title"] = "Frequently Asked Questions",
                ["faq.hero_subtitle"] = "Find answers to the most common questions about TeknoSOS.",
                ["faq.q1"] = "What is TeknoSOS?",
                ["faq.a1"] = "TeknoSOS is an online platform connecting citizens with verified technical professionals in Albania. It allows you to report defects, find professionals, and manage service requests.",
                ["faq.q2"] = "Is it free to use?",
                ["faq.a2"] = "Yes, registration and posting requests is free for citizens. Professionals may have premium plans for additional features.",
                ["faq.q3"] = "How are professionals verified?",
                ["faq.a3"] = "Every professional goes through a verification process including identity check, qualifications, and work experience review.",
                ["faq.q4"] = "How does defect reporting work?",
                ["faq.a4"] = "Log into your account, go to 'Report Defect', fill in the form with details, photos, and location. Your request will be visible to area professionals.",
                ["faq.q5"] = "Which areas are covered?",
                ["faq.a5"] = "We currently cover all of Albania, with special focus on Tirana, Durres, Vlora, Shkoder, and Elbasan.",
                ["faq.q6"] = "How can I become a professional on the platform?",
                ["faq.a6"] = "Register as a professional, complete your profile with specialties and documents, and wait for approval from our team.",
                ["faq.q7"] = "Are payments secure?",
                ["faq.a7"] = "Yes, all transactions are processed through secure systems. We do not store your card details.",
                ["faq.q8"] = "How can I contact support?",
                ["faq.a8"] = "You can contact us through the contact page, email info@teknosos.al, or phone during business hours.",

                ["terms.title"] = "Terms of Service",
                ["privacy.title"] = "Privacy Policy",
                ["cookies.title"] = "Cookie Policy",
                ["disclaimer.title"] = "Disclaimer",

                ["defects.title"] = "Defects",
                ["defects.list_title"] = "Defect List",
                ["defects.my_reports"] = "My Reports",
                ["defects.report_new"] = "Report New Defect",
                ["defects.status"] = "Status",
                ["defects.category"] = "Category",
                ["defects.priority"] = "Priority",
                ["defects.date"] = "Date",
                ["defects.location"] = "Location",
                ["defects.description"] = "Description",
                ["defects.no_reports"] = "You don't have any reports yet.",
                ["defects.details_title"] = "Defect Details",
                ["defects.status_created"] = "Created",
                ["defects.status_matched"] = "Matched",
                ["defects.status_in_progress"] = "In Progress",
                ["defects.status_completed"] = "Completed",
                ["defects.status_cancelled"] = "Cancelled",
                ["defects.status_rejected"] = "Rejected",
                ["defects.interests"] = "Technician Interests",
                ["defects.no_interests"] = "No technician interest yet.",

                ["admin.title"] = "Administration Panel",
                ["admin.dashboard"] = "Dashboard",
                ["admin.users"] = "Users",
                ["admin.defects"] = "Defects",
                ["admin.settings"] = "Settings",
                ["admin.site_settings"] = "Site Settings",
                ["admin.logo"] = "Logo",
                ["admin.colors"] = "Colors",
                ["admin.content"] = "Content",
                ["admin.languages"] = "Languages",
                ["admin.navigation"] = "Navigation",
                ["admin.total_users"] = "Total Users",
                ["admin.total_defects"] = "Total Defects",
                ["admin.pending"] = "Pending",
                ["admin.active_pros"] = "Active Professionals",

                ["common.save"] = "Save",
                ["common.cancel"] = "Cancel",
                ["common.delete"] = "Delete",
                ["common.edit"] = "Edit",
                ["common.view"] = "View",
                ["common.search"] = "Search",
                ["common.filter"] = "Filter",
                ["common.loading"] = "Loading...",
                ["common.no_results"] = "No results found.",
                ["common.confirm"] = "Confirm",
                ["common.back"] = "Back",
                ["common.next"] = "Next",
                ["common.submit"] = "Submit",
                ["common.actions"] = "Actions",
                ["common.status"] = "Status",
                ["common.active"] = "Active",
                ["common.inactive"] = "Inactive",
                ["common.role"] = "Role",
                ["common.date"] = "Date",
                ["common.all"] = "All",
            };

            // ======== ITALIAN (it) ========
            _translations["it"] = new Dictionary<string, string>
            {
                ["nav.home"] = "Home",
                ["nav.dashboard"] = "Pannello",
                ["nav.about"] = "Chi Siamo",
                ["nav.how_it_works"] = "Come Funziona",
                ["nav.contact"] = "Contatti",
                ["nav.faq"] = "FAQ",
                ["nav.login"] = "Accedi",
                ["nav.register"] = "Registrati",
                ["nav.logout"] = "Esci",
                ["nav.profile"] = "Profilo",
                ["nav.messages"] = "Messaggi",
                ["nav.report_defect"] = "Segnala Difetto",
                ["nav.my_reports"] = "I Miei Report",
                ["nav.admin"] = "Pannello Admin",
                ["nav.language"] = "Lingua",
                ["nav.technicians"] = "Tecnici",
                ["nav.notifications"] = "Notifiche",
                ["nav.terms"] = "Termini",
                ["nav.privacy"] = "Privacy",
                ["nav.cookies"] = "Cookie",
                ["nav.disclaimer"] = "Disclaimer",
                ["technicians_title"] = "I Nostri Tecnici",
                ["footer.quick_links"] = "Link Rapidi",
                ["footer.legal"] = "Legale",
                ["footer.rights"] = "Tutti i diritti riservati.",
                ["footer.made_in"] = "Fatto con amore in Albania",
                ["footer.description"] = "La piattaforma digitale leader in Albania che connette cittadini con professionisti tecnici.",
                ["footer.navigation"] = "Navigazione",
                ["footer.contact"] = "Contatti",
                ["home.title"] = "Home",
                ["home.subtitle"] = "Piattaforma Digitale di Servizi Tecnici",
                ["home.hero_title"] = "TeknoSOS",
                ["home.hero_subtitle"] = "Connettiti con professionisti certificati per tutte le tue esigenze tecniche.",
                ["home.get_started"] = "Inizia Ora",
                ["home.sign_in"] = "Accedi",
                ["home.go_dashboard"] = "Vai al Pannello",
                ["home.for_clients"] = "Per i Clienti",
                ["home.for_clients_desc"] = "Pubblica le tue esigenze di servizio e connettiti con professionisti verificati.",
                ["home.for_professionals"] = "Per i Professionisti",
                ["home.for_professionals_desc"] = "Fai crescere la tua attivita' offrendo servizi a migliaia di clienti.",
                ["home.verified"] = "Verificato e Sicuro",
                ["home.verified_desc"] = "Tutte le transazioni sono protette dalla nostra piattaforma affidabile.",
                ["home.how_it_works"] = "Come Funziona",
                ["home.step1_title"] = "Pubblica la Richiesta",
                ["home.step1_desc"] = "Descrivi il problema con foto e posizione",
                ["home.step2_title"] = "Ricevi Offerte",
                ["home.step2_desc"] = "Ricevi offerte da professionisti certificati vicini",
                ["home.step3_title"] = "Scegli e Lavora",
                ["home.step3_desc"] = "Scegli in base a recensioni e commenti",
                ["home.cta_title"] = "Pronto per iniziare?",
                ["home.cta_subtitle"] = "Unisciti a migliaia di clienti e professionisti soddisfatti",
                ["common.save"] = "Salva",
                ["common.cancel"] = "Annulla",
                ["common.delete"] = "Elimina",
                ["common.edit"] = "Modifica",
                ["common.search"] = "Cerca",
                ["common.loading"] = "Caricamento...",
                ["common.submit"] = "Invia",
                ["common.back"] = "Indietro",
                ["common.yes"] = "Si",
                ["common.no"] = "No",
            };

            // ======== GERMAN (de) ========
            _translations["de"] = new Dictionary<string, string>
            {
                ["nav.home"] = "Startseite",
                ["nav.dashboard"] = "Dashboard",
                ["nav.about"] = "Uber Uns",
                ["nav.how_it_works"] = "Wie es funktioniert",
                ["nav.contact"] = "Kontakt",
                ["nav.faq"] = "FAQ",
                ["nav.login"] = "Anmelden",
                ["nav.register"] = "Registrieren",
                ["nav.logout"] = "Abmelden",
                ["nav.profile"] = "Profil",
                ["nav.messages"] = "Nachrichten",
                ["nav.report_defect"] = "Defekt melden",
                ["nav.my_reports"] = "Meine Berichte",
                ["nav.language"] = "Sprache",
                ["nav.technicians"] = "Techniker",
                ["nav.notifications"] = "Benachrichtigungen",
                ["nav.terms"] = "AGB",
                ["nav.privacy"] = "Datenschutz",
                ["nav.cookies"] = "Cookies",
                ["nav.disclaimer"] = "Haftungsausschluss",
                ["technicians_title"] = "Unsere Techniker",
                ["footer.quick_links"] = "Schnelllinks",
                ["footer.legal"] = "Rechtliches",
                ["footer.rights"] = "Alle Rechte vorbehalten.",
                ["footer.made_in"] = "Mit Liebe gemacht in Albanien",
                ["footer.description"] = "Albaniens fuhrende digitale Plattform, die Burger mit technischen Fachleuten verbindet.",
                ["footer.navigation"] = "Navigation",
                ["footer.contact"] = "Kontakt",
                ["home.title"] = "Startseite",
                ["home.subtitle"] = "Digitale Plattform fur technische Dienstleistungen",
                ["home.hero_title"] = "TeknoSOS",
                ["home.hero_subtitle"] = "Verbinden Sie sich mit zertifizierten Fachleuten fur alle Ihre technischen Bedurfnisse.",
                ["home.get_started"] = "Jetzt starten",
                ["home.sign_in"] = "Anmelden",
                ["home.go_dashboard"] = "Zum Dashboard",
                ["home.for_clients"] = "Fur Kunden",
                ["home.for_clients_desc"] = "Veroffentlichen Sie Ihre Serviceanfragen und verbinden Sie sich mit verifizierten Fachleuten.",
                ["home.for_professionals"] = "Fur Fachleute",
                ["home.for_professionals_desc"] = "Erweitern Sie Ihr Geschaft, indem Sie Tausenden von Kunden Dienstleistungen anbieten.",
                ["home.verified"] = "Verifiziert und Sicher",
                ["home.verified_desc"] = "Alle Transaktionen sind durch unsere vertrauenswurdige Plattform geschutzt.",
                ["home.how_it_works"] = "Wie es funktioniert",
                ["home.step1_title"] = "Anfrage veroffentlichen",
                ["home.step1_desc"] = "Beschreiben Sie das Problem mit Fotos und Standort",
                ["home.step2_title"] = "Angebote erhalten",
                ["home.step2_desc"] = "Erhalten Sie Angebote von zertifizierten Fachleuten in Ihrer Nahe",
                ["home.step3_title"] = "Wahlen und Arbeiten",
                ["home.step3_desc"] = "Wahlen Sie basierend auf Bewertungen und Kommentaren",
                ["home.cta_title"] = "Bereit anzufangen?",
                ["home.cta_subtitle"] = "Schliessen Sie sich Tausenden zufriedener Kunden und Fachleute an",
                ["common.save"] = "Speichern",
                ["common.cancel"] = "Abbrechen",
                ["common.delete"] = "Loschen",
                ["common.edit"] = "Bearbeiten",
                ["common.search"] = "Suchen",
                ["common.loading"] = "Laden...",
                ["common.submit"] = "Absenden",
                ["common.back"] = "Zuruck",
                ["common.yes"] = "Ja",
                ["common.no"] = "Nein",
            };

            // ======== FRENCH (fr) ========
            _translations["fr"] = new Dictionary<string, string>
            {
                ["nav.home"] = "Accueil",
                ["nav.dashboard"] = "Tableau de bord",
                ["nav.about"] = "A propos",
                ["nav.how_it_works"] = "Comment ca marche",
                ["nav.contact"] = "Contact",
                ["nav.faq"] = "FAQ",
                ["nav.login"] = "Connexion",
                ["nav.register"] = "Inscription",
                ["nav.logout"] = "Deconnexion",
                ["nav.profile"] = "Profil",
                ["nav.messages"] = "Messages",
                ["nav.report_defect"] = "Signaler un Defaut",
                ["nav.my_reports"] = "Mes Rapports",
                ["nav.language"] = "Langue",
                ["nav.technicians"] = "Techniciens",
                ["nav.notifications"] = "Notifications",
                ["nav.terms"] = "Conditions",
                ["nav.privacy"] = "Confidentialite",
                ["nav.cookies"] = "Cookies",
                ["nav.disclaimer"] = "Avertissement",
                ["technicians_title"] = "Nos Techniciens",
                ["footer.quick_links"] = "Liens rapides",
                ["footer.legal"] = "Juridique",
                ["footer.rights"] = "Tous droits reserves.",
                ["footer.made_in"] = "Fait avec amour en Albanie",
                ["footer.description"] = "La premiere plateforme numerique d'Albanie reliant les citoyens aux professionnels techniques.",
                ["footer.navigation"] = "Navigation",
                ["footer.contact"] = "Contact",
                ["home.title"] = "Accueil",
                ["home.subtitle"] = "Plateforme Numerique de Services Techniques",
                ["home.hero_title"] = "TeknoSOS",
                ["home.hero_subtitle"] = "Connectez-vous avec des professionnels certifies pour tous vos besoins techniques.",
                ["home.get_started"] = "Commencer",
                ["home.sign_in"] = "Se connecter",
                ["home.go_dashboard"] = "Aller au Tableau de bord",
                ["home.for_clients"] = "Pour les Clients",
                ["home.for_clients_desc"] = "Publiez vos besoins de service et connectez-vous avec des professionnels verifies.",
                ["home.for_professionals"] = "Pour les Professionnels",
                ["home.for_professionals_desc"] = "Developpez votre activite en offrant des services a des milliers de clients.",
                ["home.verified"] = "Verifie et Securise",
                ["home.verified_desc"] = "Toutes les transactions sont protegees par notre plateforme de confiance.",
                ["home.how_it_works"] = "Comment ca marche",
                ["home.step1_title"] = "Publier la Demande",
                ["home.step1_desc"] = "Decrivez le probleme avec photos et localisation",
                ["home.step2_title"] = "Recevoir des Offres",
                ["home.step2_desc"] = "Recevez des offres de professionnels certifies pres de chez vous",
                ["home.step3_title"] = "Choisir et Travailler",
                ["home.step3_desc"] = "Choisissez selon les avis et commentaires",
                ["home.cta_title"] = "Pret a commencer?",
                ["home.cta_subtitle"] = "Rejoignez des milliers de clients et professionnels satisfaits",
                ["common.save"] = "Sauvegarder",
                ["common.cancel"] = "Annuler",
                ["common.delete"] = "Supprimer",
                ["common.edit"] = "Modifier",
                ["common.search"] = "Rechercher",
                ["common.loading"] = "Chargement...",
                ["common.submit"] = "Soumettre",
                ["common.back"] = "Retour",
                ["common.yes"] = "Oui",
                ["common.no"] = "Non",
            };
        }
    }
}
